//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krakflix.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Serie()
        {
            this.Chapters = new HashSet<Chapter>();
        }
    
        public string IdSerie { get; set; }
        public string Title { get; set; }
        public int NumTemp { get; set; }
        public int IdGenre { get; set; }
        public int Year { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<int> NumCap { get; set; }
        public int IdUser { get; set; }
        public string PhotoPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chapter> Chapters { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual User User { get; set; }
    }
}
